os: linux
dist: focal
language: cpp

addons:
  apt:
    packages:
    - ninja-build

env:
  global:
    CMAKE_GENERATOR=Ninja

jobs:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'        
        packages:
          - libboost-dev
          - libboost-test-dev
          - cmake 
          - ninja-build
    env:
      MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      TARGET=x86_64-linux-gnu

before_install:
  eval "${MATRIX_EVAL}"

script:
  - pwd
  - mkdir 3rd-party && cd 3rd-party
  - git clone https://github.com/johnmcfarlane/cnl.git && cd ..
  - mkdir bin && mkdir build && cd build
  - cmake .. && ninja
