os: linux
dist: focal
language: cpp

addons:
  apt:
    packages:
    - ninja-build

env:
  global:
    CMAKE_GENERATOR=Ninja

jobs:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'        
        packages:
          - libboost-dev
          - libboost-test-dev
          - cmake 
          - ninja-build
    env:
      MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      TARGET=x86_64-linux-gnu

before_install:
  eval "${MATRIX_EVAL}"

script:
  - mkdir ../3rd-party && cd ../3rd-party
  - wget https://github.com/johnmcfarlane/cnl/archive/refs/tags/v1.1.2.tar.gz && tar -xvf v1.1.2.tar.gz && rm v1.1.2.tar.gz && mv cnl-1.1.2 cnl && cd ..
  - mkdir ml/bin && mkdir ml/build && cd ml/build
  - cmake .. && ninja
